version: "3.9"

services:
  redis_server:
    image: redis:7
    ports:
      - "6379:6379"

  django_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis_server

  celery_worker:
    build: .
    command: /bin/bash -c "source /opt/conda/etc/profile.d/conda.sh && conda activate app_env && celery -A testaskdjango worker --loglevel=info"
    depends_on:
      - redis_server
      - django_app

  celery_beat:
    build: .
    command: /bin/bash -c "source /opt/conda/etc/profile.d/conda.sh && conda activate app_env && celery -A testaskdjango beat --loglevel=info"
    depends_on:
      - redis_server
      - django_app
